#!/bin/sh
# see /etc/pihole/config.list to see names associated with these IP
# addresses
ettercap -Tz --daemon -j /home/pi/lan-hosts --filter /home/pi/drop-all.ef \
         -M arp:remote /10.20.30.1// /10.20.30.33\;10.20.30.85\;10.20.30.123\;10.20.30.127\;10.20.30.133\;10.20.30.135\;10.20.30.247//
